name: Sync branch with NYPL
on:
  schedule:
    - cron:  '0 7 * * *'

  workflow_dispatch:

jobs:
  sync_with_nypl:
    runs-on: ubuntu-latest

    env:
      UPSTREAM_ORG: NYPL-Simplified
      UPSTREAM_REPO: circulation
      UPSTREAM_BRANCH: develop
      ORIGIN_BRANCH: nypl/develop

    steps:
      - name: Checkout repo to sync
        uses: actions/checkout@v2
        with:
          path: code
          
      - name: Checkout CI scripts
        uses: actions/checkout@v2
        with:
          repository: 'ThePalaceProject/ci-scripts'
          path: ci
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install Python requirements
        run: pip install -r ci/sync-requirements.txt
        
      - name: Sync branch with upstream
        run: python ci/sync.py code
